name       : semantik
version    : 1.2.10
release    : 12
source     :
    - https://waf.io/semantik-1.2.10.tar.bz2 : e5a33968461d1a47731fe0a5ce265ce507c5000a1f8b5a4ac5314f1ca055f2af
license    : GPL-3.0-or-later
component  : desktop.kde
summary    : A mind-mapping application for KDE
description: |
    Semantik (formerly kdissert) is a mind-mapping application for KDE that helps creating documents such as reports or presentations.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - kdelibs4support-devel
setup      : |
    %waf_configure
build      : |
    %waf_build
install    : |
    %waf_install --noldconfig --nomimes --nogtkicons
