name       : semantik
version    : 1.0.1
release    : 1
source     :
    - https://waf.io/semantik-1.0.1.tar.bz2 : 91e97799262611a2a6ed2930b19fd902626ff0c64e02cb2f46f481e9d09a7429
license    : GPL-3.0
component  : desktop.kde
summary    : A mind-mapping application for KDE
description: |
    Semantik (formerly kdissert) is a mind-mapping application for KDE that helps creating documents such as reports or presentations.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.6)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - kdelibs4support-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
setup      : |
    %waf_configure
build      : |
    %waf_build
install    : |
    %waf_install

    mkdir -p $installdir/usr/share/icons/hicolor/scalable/apps
    ln -s /usr/share/icons/oxygen/scalable/apps/semantik.svg $installdir/usr/share/icons/hicolor/scalable/apps/semantik.svg
    ln -s /usr/share/icons/oxygen/scalable/apps/semantik-d.svg $installdir/usr/share/icons/hicolor/scalable/apps/semantik-d.svg
