name       : semantik
version    : 1.2.7
release    : 9
source     :
    - https://waf.io/semantik-1.2.7.tar.bz2 : 6544bb9aef29a680570eae864986ef56fd45b75778f38c85efd99f20b82f069d
license    : GPL-3.0-or-later
component  : desktop.kde
summary    : A mind-mapping application for KDE
description: |
    Semantik (formerly kdissert) is a mind-mapping application for KDE that helps creating documents such as reports or presentations.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - kdelibs4support-devel
environment: |
    export CXXFLAGS="$CXXFLAGS -I/usr/include/KF5/KIOCore        -I/usr/include/KF5/KCoreAddons \
                               -I/usr/include/KF5/KConfigCore    -I/usr/include/KF5/KWidgetsAddons \
                               -I/usr/include/KF5/KI18n          -I/usr/include/KF5/KIOWidgets \
                               -I/usr/include/KF5/KConfigWidgets -I/usr/include/KF5/KConfigGui \
                               -I/usr/include/KF5/KXmlGui        -I/usr/include/KF5/KAuthCore \
                               -I/usr/include/KF5/SonnetUi"
setup      : |
    %waf_configure
build      : |
    %waf_build
install    : |
    %waf_install --noldconfig --nomimes --nogtkicons
