name       : semantik
version    : 1.2.2
release    : 5
source     :
    - https://waf.io/semantik-1.2.2.tar.bz2 : 85d1316aac1c49b667608d032c09fec299e6c3f29be94f5ed911276601849e8a
license    : GPL-3.0-or-later
component  : desktop.kde
summary    : A mind-mapping application for KDE
description: |
    Semantik (formerly kdissert) is a mind-mapping application for KDE that helps creating documents such as reports or presentations.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - kdelibs4support-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
setup      : |
    %waf_configure
build      : |
    %waf_build
install    : |
    %waf_install --noldconfig --nomimes --nogtkicons
